apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('profile/', views.ProfileDetail.as_view(), name='profile_detail'),
    path('profile/edit/', views.ProfileUpdate.as_view(), name='profile_update'),
]

whatsupmovie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('movies/', include('apps.movies.urls')),
    path('', lambda r: redirect('movies:list'), name='root')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

def profile_image_path(instance, filename):
    return 'accounts/{}/{}'.format(instance.user.username, filename)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=20, blank=True)
    about = models.CharField(max_length=140, blank=True)    
    image = ProcessedImageField(
        upload_to=profile_image_path,
        processors=[ResizeToFill(150, 150)],
        format='PNG',
        blank=True,
    )
    
    def __str__(self):
        return self.nickname

    def get_absolute_url(self):
        return reverse('accounts:profile_detail')

    def image_url(self):
        return self.image.url if self.image else '/static/images/user_dark.png' # set default image

apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm


class ProfileForm(forms.ModelForm):
    nickname = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control profile-input'}), required=False)
    about = forms.CharField(widget=forms.Textarea(attrs={'class':'noresize form-control profile-input', 'rows':4}), required=False)
    image = forms.FileField(widget=forms.FileInput(attrs={'class':'custom-file-input profile-input has-content'}), required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if getattr(self.instance, key) != '':
                field.widget.attrs['class'] += ' has-content'

    class Meta:
        model = Profile
        fields = ['nickname','about','image',]


class BootstrapUserCreationForm(UserCreationForm):
    error_css_class = 'is-invalid'


class BootstrapPasswordChangeForm(PasswordChangeForm):
    error_css_class = 'is-invalid'

apps/accounts/views.py
from django.shortcuts import render
from django.conf import settings
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login
from .models import Profile
from .forms import ProfileForm, BootstrapUserCreationForm, BootstrapPasswordChangeForm


class Login(LoginView):
    redirect_authenticated_user = True


class Logout(LogoutView):
    pass


class Signup(CreateView):
    model = settings.AUTH_USER_MODEL
    form_class = BootstrapUserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('movies:list')

    def form_valid(self, form):
        response = super().form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        Profile.objects.create(user=user)
        login(self.request, user)
        return response


class PasswordChange(PasswordChangeView):
    template_name = 'accounts/password_change_form.html'
    form_class = BootstrapPasswordChangeForm
    success_url = reverse_lazy('accounts:profile_detail')


class ProfileDetail(LoginRequiredMixin, DetailView):
    def get_object(self):
        return self.request.user.profile


class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm

    def get_object(self):
        return self.request.user.profile

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().user != self.request.user:
            return HttpResponseForbidden("You are not allowed to edit this Profile.")
        return super().dispatch(request, *args, **kwargs)

apps/accounts/templates/accounts/password_change_form.html
{% extends 'base.html' %}

{% load account_extras %}

{% block container %}

<div class="row flex-column accounts">
  <div class="col-11 offset-sm-1 col-sm-10 offset-md-2 col-md-8">
    <h1 class="py-4">비밀번호 변경</h1>

    <div class="mt-3 mb-5">
      {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors | join:'<br>' | safe }}
      </div>
      {% endif %}
      <form method="post">
        {% csrf_token %}
        <div class="form-group profile-form">
          {{ form.old_password | add_class:'form-control profile-input' }}
          <label for="{{ form.old_password.id_for_label }}">기존 비밀번호</label>
          {% for error in form.old_password.errors %}
            <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <div class="form-group profile-form">
          {{ form.new_password1 | add_class:'form-control profile-input' }}
          <label for="{{ form.new_password1.id_for_label }}">새 비밀번호</label>
          <small class="form-text text-muted">{{ form.new_password1.help_text | li_to_br | safe }}</small>
          {% for error in form.new_password1.errors %}
            <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <div class="form-group profile-form">
          {{ form.new_password2 | add_class:'form-control profile-input' }}
          <label for="{{ form.new_password2.id_for_label }}">새 비밀번호 확인</label>
          {% for error in form.new_password2.errors %}
            <div class="invalid-feedback">{{ error }}</div>
          {% endfor %}
        </div>
        <input type="submit" value="변경하기" class="btn btn-movie mt-2">
      </form>
    </div>
  </div>
</div>

<script>
  const inputOldPw = document.querySelector(".profile-form input#id_old_password")
  const inputNewPw1 = document.querySelector(".profile-form input#id_new_password1")
  const inputNewPw2 = document.querySelector(".profile-form input#id_new_password2")

  function focusOut() {
      if (this.value != ""){
          this.classList.add("has-content");
      } else {
          this.classList.remove("has-content")
      }
  }

  inputOldPw.addEventListener("focusout", focusOut);
  inputNewPw1.addEventListener("focusout", focusOut);
  inputNewPw2.addEventListener("focusout", focusOut);
</script>

{% endblock %}

apps/accounts/templates/accounts/profile_detail.html
{% extends 'base.html' %}

{% block container %}

<div class="row flex-column accounts text-center">
  <div class="col-11 offset-sm-1 col-sm-10 offset-md-2 col-md-8">
    <h1 class="my-5 profile-title">계정 정보</h1>
    <div>
      <img src="{{ user.profile.image_url }}" alt="profile image" width="150">  
    </div>

    <div class="mt-3 mb-5 profile-content">
      <div class="my-3">
        <span>사용자 이름</span>
        <p>{{ user.username }}</p>
      </div>
      <div class="my-3">
        <span>별명</span>
        <p>{{ user.profile.nickname | default:'-' }}</p>
      </div>
      <div class="my-3">
        <span>자기소개</span>
        <p>{{ user.profile.about | default:'-' }}</p>
      </div>
    </div>

    <div class="pb-5">
      <a class="btn btn-movie-sub" href="{% url 'accounts:profile_update' %}">프로필 수정</a>
      <a class="btn btn-movie" href="{% url 'accounts:password_change' %}">비밀번호 변경</a>
    </div>
  </div>
</div>

{% endblock %}

apps/accounts/templates/accounts/profile_form.html
{% extends 'base.html' %}

{% block container %}

<div class="row flex-column accounts">
  <div class="col-11 offset-sm-1 col-sm-10 offset-md-2 col-md-8">
    <h1 class="profile-title">프로필 수정</h1>

    <div class="my-5">
      {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors | join:'<br>' | safe }}
      </div>
      {% endif %}
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group profile-form">
          {{ form.nickname }}
          <label for="{{ form.nickname.id_for_label }}">별명</label>
          {{ form.nickname.errors }}
        </div>
        <div class="form-group profile-form">
          {{ form.about }}
          <label for="{{ form.about.id_for_label }}">자기소개</label>
          {{ form.about.errors }}
        </div>
        <div class="form-group profile-form">
          <div class="custom-file">
            {{ form.image }}
            <label for="{{ form.image.id_for_label }}">프로필 사진</label>
            {{ form.image.errors }}
          </div>
          <label id="label_image" class="custom-file-label profile-extra-label" for="{{ form.image.id_for_label }}"></label>
        </div>
        <input type="submit" value="수정하기" class="btn btn-movie mt-2">
      </form>
    </div>
  </div>
</div>

<script>
  document.getElementById('id_image').addEventListener('change', function(e) {
    document.getElementById('label_image').innerHTML = event.target.files[0].name;
  })

  const inputNickname = document.getElementById("id_nickname");
  const inputAbout = document.getElementById("id_about");

  function focusOut() {
    if (this.value != ""){
        this.classList.add("has-content");
    } else {
        this.classList.remove("has-content")
    }
  }

  inputNickname.addEventListener("focusout", focusOut);
  inputAbout.addEventListener("focusout", focusOut);
</script>

{% endblock %}