apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('profile/', views.ProfileDetail.as_view(), name='profile_detail'),
    path('profile/edit/', views.ProfileUpdate.as_view(), name='profile_update'),
]

apps/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.MovieList.as_view(), name='list'),
    path('recommend/', views.MovieRecommend.as_view(), name='recommend'),
    path('<int:pk>/', views.MovieDetail.as_view(), name='detail'),
    path('<int:movie_id>/ratings/new', views.RatingCreate.as_view(), name='ratings_create'),
    path('<int:movie_id>/ratings/<int:pk>/delete', views.RatingDelete.as_view(), name='ratings_delete'),
]

whatsupmovie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('movies/', include('apps.movies.urls')),
    path('', lambda r: redirect('movies:list'), name='root')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whatsupmovie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>What's up Movie</title>

  <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/font.css' %}">
  <link rel="stylesheet" href="{% static 'css/star.css' %}">
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="/">What's up movie</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <a class="nav-item nav-link {% if request.path == '/movies/' %}active{% endif %}" href="{% url 'movies:list' %}">영화 목록</a>
          <a class="nav-item nav-link {% if request.path == '/movies/recommend/' %}active{% endif %}" href="{% url 'movies:recommend' %}">추천 영화</a>
          <a class="nav-item nav-link nav-border {% if request.path == '/accounts/profile/' %}active{% endif %}" href="{% url 'accounts:profile_detail'%}">
            <img src="{{ user.profile.image_url }}" alt="profile image" width="30">  
            {% firstof user.profile.nickname user.username %}
          </a>
          <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
        {% else %}
          <a class="nav-item nav-link" href="{% url 'accounts:login' %}">로그인</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container">
  {% block container %}{% endblock %}    
  </div>

  <script type="text/javascript" src="{% static 'jquery/dist/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'popper.js/dist/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>