apps/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.MovieList.as_view(), name='list'),
    path('recommend/', views.MovieRecommend.as_view(), name='recommend'),
    path('<int:pk>/', views.MovieDetail.as_view(), name='detail'),
    path('<int:movie_id>/ratings/new', views.RatingCreate.as_view(), name='ratings_create'),
    path('<int:movie_id>/ratings/<int:pk>/delete', views.RatingDelete.as_view(), name='ratings_delete'),
]

whatsupmovie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('movies/', include('apps.movies.urls')),
    path('', lambda r: redirect('movies:list'), name='root')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/movies/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from imagekit.models import ProcessedImageField # 'pip install pillow pilkit django-imagekit' required
from imagekit.processors import ResizeToFill

def movie_image_path(instance, filename):
    return 'movies/{}/{}'.format('images', filename) # Can set storing path using instance object's data

class Movie(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = ProcessedImageField(
        upload_to=movie_image_path,
        processors=[ResizeToFill(400, 600)],
        format='PNG', # or JPEG, etc.
        blank=True,
    ) 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def get_avg_rating(self):
        return self.rating_set.aggregate(models.Avg('score'))['score__avg'] or 0.0

    def image_url(self):
        return self.image.url if self.image else '/static/images/popcorn.jpg' # Set default image


class Rating(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    score = models.FloatField(default=0.0)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('movie', 'user')

    def __str__(self):
        return str(self.score)

    def get_absolute_url(self):
        return reverse('movies:detail', kwargs={'pk':self.movie_id})

apps/movies/forms.py
from django import forms
from .models import Rating


class RatingForm(forms.ModelForm):
    SCORES = (
        (5.0,'5.0'),
        (4.5,'4.5'),
        (4.0,'4.0'),
        (3.5,'3.5'),
        (3.0,'3.0'),
        (2.5,'2.5'),
        (2.0,'2.0'),
        (1.5,'1.5'),
        (1.0,'1.0'),
        (0.5,'0.5'),
    )
    score = forms.ChoiceField(choices=SCORES, widget=forms.RadioSelect(), initial=(2.5, '2.5'))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'noresize form-control comment-textarea', 'placeholder':'리뷰를 작성하세요!', 'rows':'1'}))

    class Meta:
        model = Rating
        fields = ['score','content',]

apps/movies/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from .models import Movie, Rating
from .forms import RatingForm
from .services import get_recommended_movies


class MovieList(ListView):
    model = Movie
    context_object_name = 'movies'
    paginate_by = 12


class MovieDetail(DetailView):
    model = Movie

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rating_form'] = RatingForm()
        if self.request.user.is_authenticated:
            context['rating_exists'] = self.object.rating_set.filter(user=self.request.user).exists()
        return context


class RatingCreate(LoginRequiredMixin, CreateView):
    http_method_names = ['post',]
    model = Rating
    form_class = RatingForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.movie_id = self.kwargs.get('movie_id')
        return super().form_valid(form)


class RatingDelete(LoginRequiredMixin, DeleteView):
    http_method_names = ['post',]
    model = Rating

    def get_success_url(self):
        return reverse('movies:detail', kwargs={'pk':self.kwargs.get('movie_id')})

    def delete(self, request, *args, **kwargs):
        if self.get_object().user != self.request.user:
            return HttpResponseForbidden("You are not allowed to delete this Comment")
        return super().delete(request, *args, **kwargs)


class MovieRecommend(LoginRequiredMixin, TemplateView):
    template_name = 'movies/movie_recommend.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.rating_set.count() < 3:
            context['not_ready'] = '영화 추천을 위하여 3개의 영화에 평점을 매겨주세요.'
        else:
            context['recommended_movies'] = get_recommended_movies(self.request.user)
        return context

apps/movies/templates/movies/movie_detail.html
{% extends 'base.html' %}

{% load movie_extras %}

{% block container %}

<div class="movie-detail-bg">
    <img src="{{ movie.image_url }}" alt="Movie Image">
</div>
<div class="row movie-detail-item">
  <div class="offset-2 col-8 offset-sm-0 col-sm-4 col-md-4 col-lg-4 col-xl-4">
    <img src="{{ movie.image_url }}" class="w-100" alt="Movie Image">    
  </div>
  <div class="col-12 col-sm-8 col-md-8 col-lg-8 col-xl-8 movie-item-text">
    <h1 class="my-5">{{ movie.title }}</h1>
    <div class="mb-4">
      <h5>
        <span class="badge badge-movie">&starf; {{ movie.get_avg_rating | floatformat:2 }}</span>
      </h5>
      <p>{{ movie.content }}</p>
    </div>  
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h3 class="small-title">리뷰</h3>

    {% if user.is_authenticated %}
      {% if not rating_exists %}
        
        {{ form.non_field_errors }}
        <form action="{% url 'movies:ratings_create' movie.pk %}" method="post">
          {% csrf_token %}
          <div class="form-group form-comment">
            <div>
              <div class="comment-name-tag">
                <img src="{{ user.profile.image_url }}" alt="profile image" width="30">  
                {% firstof user.profile.nickname user.username %}
              </div>
              <fieldset class="rating">
                {% for choice in rating_form.score.field.choices %}
                  <input type="radio" id="star{{ choice.1 | remove_dot }}" name="score" value="{{ choice.0 }}" required {% if choice.0 == 3.5 %}checked{% endif %}/><label class="{{ choice.1 | last_char_is_equal_to:'0' | yesno:'full,half' }}" for="star{{ choice.1 | remove_dot }}"></label>
                {% endfor %}
              </fieldset>
              {{ rating_form.score.errors }}
            </div>
            <div class="comment-text-submit">
                {{ rating_form.content }}
                {{ rating_form.content.errors }}
              <input type="submit" value="작성" class="btn btn-movie">
            </div>
          </div>
        </form>
        
      {% endif %}
    {% endif %}

    <dl class="my-5">
      {% for rating in movie.rating_set.all %}
      <dt class="mb-1">
        {% firstof rating.user.profile.nickname rating.user.username %}<span class="badge badge-movie ml-2">&starf; {{ rating.score }}</span>
      </dt>
      <div class="d-flex">
        <dd>
          {{ rating.content }}
          {% if user == rating.user %}
        </dd>
        <form action="{% url 'movies:ratings_delete' movie.pk rating.pk %}" method="post" style="display: inline-block;">
          {% csrf_token %}
          <input type="submit" value="삭제" class="btn btn-movie py-0 px-1">
        </form>
        {% endif %}
      </div>
      <hr>
      {% endfor %}
    </dl>
  </div>
</div>

<script>
  const textarea = document.querySelector(".comment-textarea");

  textarea.oninput = function() {
    textarea.style.height = "";
    textarea.style.height = Math.min(textarea.scrollHeight) + "px";
  }
</script>

{% endblock %}

apps/movies/templates/movies/movie_list.html
{% extends 'base.html' %}

{% load movie_extras %}

{% block container %}

<h1 class="my-5 big-title">영화 목록</h1>

<div class="row pb-4 movie-list">
  {% for movie in movies %}
  <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-5">
    <a href="{% url 'movies:detail' movie.pk %}" class="card-wrapper">
      <div class="card">
        <img class="card-img-top" src="{{ movie.image_url }}" alt="Movie Image">
        <div class="card-body">
          <span class="badge badge-movie">&starf; {{ movie.get_avg_rating | floatformat:2 }}</span>
          <h5 class="card-title">
            {{ movie.title }}
          </h5>
        </div>
      </div>
    </a>
  </div>
  {% endfor %}
</div>

{% if is_paginated %}
<nav class="pt-4 pb-5">
  <ul class="pagination justify-content-center">
    {% if page_obj.number == 1 %}
      <li class="page-item disabled">
        <span class="page-link">&laquo;</span>
      </li>
    {% else %}
      <li class="page-item">
        <a class="page-link" href="?page=1">&laquo;</a>
      </li>
    {% endif %}
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">&lsaquo;</span>
      </li>
    {% endif %}
    {% for i in paginator|proper_paginate:page_obj.number %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <span class="page-link">
            {{ i }}
            <span class="sr-only">(current)</span>
          </span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">&rsaquo;</span>
      </li>
    {% endif %}
    {% if page_obj.number == paginator.num_pages %}
      <li class="page-item disabled">
        <span class="page-link">&raquo;</span>
      </li>
    {% else %}
      <li class="page-item">
        <a class="page-link" href="?page={{ paginator.num_pages }}">&raquo;</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

{% endblock %}

apps/movies/templates/movies/movie_recommend.html
{% extends 'base.html' %}

{% block container %}

<h1 class="my-5 big-title">추천 영화</h1>
  
<div class="row movie-list">
{% if not_ready %}
  <div class="col-12 my-5">
    <div class="card">
      <div class="card-body">
        {{ not_ready }}
      </div>
    </div>
  </div>
{% else %}
  {% for _, movie in recommended_movies %}
  <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-5">
    <a href="{% url 'movies:detail' movie.pk %}" class="card-wrapper">
      <div class="card">
        <img class="card-img-top" src="{{ movie.image_url }}" alt="Movie Poster">
        <div class="card-body">
          <span class="badge badge-dark">&starf; {{ movie.get_avg_rating | floatformat:2 }}</span>
          <h5 class="card-title">
            {{ movie.title }}
          </h5>
        </div>
      </div>
    </a>
  </div>
  {% endfor %}
{% endif %}
</div>

{% endblock %}